kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  # Extra stuff needed for ingress per https://kind.sigs.k8s.io/docs/user/ingress/#create-cluster
  kubeadmConfigPatches:
  - |
    kind: InitConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-labels: "ingress-ready=true"
  extraPortMappings:
  - containerPort: 30080
    hostPort: 30080
    protocol: TCP
  - containerPort: 30443
    hostPort: 443
    protocol: TCP
# extra path for our own Docker registry per https://raw.githubusercontent.com/kubernetes-sigs/kind/2e6414694724a44803caff801eeee2b62a5b6765/site/static/examples/kind-with-registry.sh
containerdConfigPatches:
- |-
  [plugins."io.containerd.grpc.v1.cri".registry]
    config_path = "/etc/containerd/certs.d"
